import { createHash, randomUUID } from 'node:crypto';
import type { Pool, PoolConnection, RowDataPacket } from 'mysql2/promise';
import { AppError } from '../../../shared/http/errors.ts';
import type { EmailTemplateRepository, ClaimedTemplateTest, TemplateRecord, TemplateSummary, TemplateTest, TemplateVersion } from './email-template-repository.ts';
import { defaults, definition, keySchema, type EmailContent, type TemplateKey } from './template-content.ts';

type TemplateRow=RowDataPacket&{template_key:string;draft_text:string|null;draft_revision:string;published_version:number|null;updated_by:string|null;updated_at:Date};
type VersionRow=RowDataPacket&{version:number;content_text:string;actor_public_id:string;reason:string;created_at:Date};
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const mask=(email:string)=>{const at=email.lastIndexOf('@');return at<1?'***':email[0]+'***'+email.slice(at);};
const content=(key:TemplateKey,value:string|null):EmailContent=>value?JSON.parse(value) as EmailContent:defaults(key);
function record(row:TemplateRow):TemplateRecord{const key=keySchema.parse(row.template_key);return{key,content:content(key,row.draft_text),draftRevision:row.draft_revision,publishedVersion:row.published_version===null?null:Number(row.published_version),updatedAt:row.updated_at,updatedBy:row.updated_by};}

export class MySqlEmailTemplateRepository implements EmailTemplateRepository{
  readonly#pool:Pool;constructor(pool:Pool){this.#pool=pool;}
  async list():Promise<TemplateSummary[]>{const[rows]=await this.#pool.execute<TemplateRow[]>('SELECT template_key,draft_text,draft_revision,published_version,updated_by,updated_at FROM email_templates ORDER BY template_key');return rows.map(row=>{const r=record(row),d=definition(r.key);return{key:r.key,label:d.label,purpose:d.key.split('.')[0]!,draftRevision:r.draftRevision,publishedVersion:r.publishedVersion,updatedAt:r.updatedAt,updatedBy:r.updatedBy};});}
  async detail(key:TemplateKey):Promise<TemplateRecord>{const[rows]=await this.#pool.execute<TemplateRow[]>('SELECT template_key,draft_text,draft_revision,published_version,updated_by,updated_at FROM email_templates WHERE template_key=?',[key]);if(!rows[0])throw missing();return record(rows[0]);}
  async published(key:TemplateKey,selectedVersion?:number|null):Promise<{content:EmailContent;version:number|null}>{
    if(selectedVersion!==undefined){if(selectedVersion!==null&&selectedVersion>0){const v=await this.version(key,selectedVersion);return{content:v.content,version:v.version};}return{content:defaults(key),version:null};}
    const detail=await this.detail(key);if(!detail.publishedVersion)return{content:defaults(key),version:null};const v=await this.version(key,detail.publishedVersion);return{content:v.content,version:v.version};
  }
  async saveDraft(actor:string,key:TemplateKey,expectedRevision:string,next:EmailContent):Promise<TemplateRecord>{const revision=randomUUID();const[result]=await this.#pool.execute<any>('UPDATE email_templates SET draft_text=?,draft_revision=?,updated_by=?,updated_at=UTC_TIMESTAMP() WHERE template_key=? AND draft_revision=?',[JSON.stringify(next),revision,actor,key,expectedRevision]);if(result.affectedRows!==1)throw conflict();return this.detail(key);}
  async publish(actor:string,key:TemplateKey,draftRevision:string,expectedVersion:number|null,reason:string,idempotencyKey:string,requestId:string){return this.#transaction(async c=>{
    const prior=await this.#idempotent(c,actor,idempotencyKey,'publish',key,{draftRevision,expectedVersion,reason});if(prior)return prior as {publishedVersion:number;publishedAt:Date};
    const[rows]=await c.execute<TemplateRow[]>('SELECT template_key,draft_text,draft_revision,published_version,updated_by,updated_at FROM email_templates WHERE template_key=? FOR UPDATE',[key]);const row=rows[0];if(!row)throw missing();if(row.draft_revision!==draftRevision||Number(row.published_version??0)!==Number(expectedVersion??0))throw conflict();
    const version=Number(row.published_version??0)+1,publishedAt=new Date();await c.execute('INSERT INTO email_template_versions(template_key,version,content_text,actor_public_id,reason,created_at) VALUES(?,?,?,?,?,?)',[key,version,row.draft_text??JSON.stringify(defaults(key)),actor,reason,publishedAt]);await c.execute('UPDATE email_templates SET published_version=?,updated_by=?,updated_at=? WHERE template_key=?',[version,actor,publishedAt,key]);const result={publishedVersion:version,publishedAt};await this.#remember(c,actor,idempotencyKey,'publish',key,{draftRevision,expectedVersion,reason},result,reason,requestId);return result;
  });}
  async versions(key:TemplateKey,limit:number,cursor:number|null){const values=cursor?[key,cursor,limit+1]:[key,limit+1],where=cursor?'AND version<?':'';const[rows]=await this.#pool.execute<VersionRow[]>(`SELECT version,content_text,actor_public_id,reason,created_at FROM email_template_versions WHERE template_key=? ${where} ORDER BY version DESC LIMIT ?`,values);const items=rows.slice(0,limit).map(version);return{items,nextCursor:rows.length>limit?items.at(-1)!.version:null};}
  async version(key:TemplateKey,value:number):Promise<TemplateVersion>{const[rows]=await this.#pool.execute<VersionRow[]>('SELECT version,content_text,actor_public_id,reason,created_at FROM email_template_versions WHERE template_key=? AND version=?',[key,value]);if(!rows[0])throw missing('Versi template tidak ditemukan.');return version(rows[0]);}
  async restore(actor:string,key:TemplateKey,value:number,expectedRevision:string,reason:string,idempotencyKey:string,requestId:string){return this.#transaction(async c=>{
    const prior=await this.#idempotent(c,actor,idempotencyKey,'restore',key,{value,expectedRevision,reason});if(prior)return prior as TemplateRecord;
    const[templates]=await c.execute<TemplateRow[]>('SELECT template_key,draft_text,draft_revision,published_version,updated_by,updated_at FROM email_templates WHERE template_key=? FOR UPDATE',[key]);if(!templates[0])throw missing();if(templates[0].draft_revision!==expectedRevision)throw conflict();const[versions]=await c.execute<VersionRow[]>('SELECT version,content_text,actor_public_id,reason,created_at FROM email_template_versions WHERE template_key=? AND version=?',[key,value]);if(!versions[0])throw missing('Versi template tidak ditemukan.');const revision=randomUUID(),now=new Date();await c.execute('UPDATE email_templates SET draft_text=?,draft_revision=?,updated_by=?,updated_at=? WHERE template_key=?',[versions[0].content_text,revision,actor,now,key]);const result=record({...templates[0],draft_text:versions[0].content_text,draft_revision:revision,updated_by:actor,updated_at:now});await this.#remember(c,actor,idempotencyKey,'restore',key,{value,expectedRevision,reason},result,reason,requestId);return result;
  });}
  async enqueueTest(actor:string,key:TemplateKey,draftRevision:string,idempotencyKey:string,requestId:string){return this.#transaction(async c=>{
    const payload={draftRevision};const prior=await this.#idempotent(c,actor,idempotencyKey,'test',key,payload);if(prior)return prior as TemplateTest;const[templates]=await c.execute<TemplateRow[]>('SELECT template_key,draft_text,draft_revision,published_version,updated_by,updated_at FROM email_templates WHERE template_key=? FOR UPDATE',[key]);const row=templates[0];if(!row)throw missing();if(row.draft_revision!==draftRevision)throw conflict();const[users]=await c.execute<Array<RowDataPacket&{email:string}>>("SELECT email FROM users WHERE public_id=? AND status='active' AND email_verified_at IS NOT NULL",[actor]);if(!users[0])throw new AppError(422,'TEST_RECIPIENT_UNAVAILABLE','Akun Super Admin belum memiliki email terverifikasi.');const testId=randomUUID(),now=new Date(),result={testId,status:'queued' as const,maskedRecipient:mask(users[0].email),errorCode:null};await c.execute('INSERT INTO email_template_tests(public_id,template_key,actor_public_id,content_text,status,created_at,updated_at) VALUES(?,?,?,?,\'queued\',?,?)',[testId,key,actor,row.draft_text??JSON.stringify(defaults(key)),now,now]);await this.#remember(c,actor,idempotencyKey,'test',key,payload,result,null,requestId);return result;
  });}
  async testStatus(actor:string,key:TemplateKey,testId:string):Promise<TemplateTest>{const[rows]=await this.#pool.execute<Array<RowDataPacket&{public_id:string;status:TemplateTest['status'];email:string;error_code:string|null}>>('SELECT t.public_id,t.status,u.email,t.error_code FROM email_template_tests t JOIN users u ON u.public_id=t.actor_public_id WHERE t.public_id=? AND t.template_key=? AND t.actor_public_id=?',[testId,key,actor]);if(!rows[0])throw missing('Email uji tidak ditemukan.');return{testId:rows[0].public_id,status:rows[0].status,maskedRecipient:mask(rows[0].email),errorCode:rows[0].error_code};}
  async claimTest():Promise<ClaimedTemplateTest|null>{return this.#transaction(async c=>{const[rows]=await c.execute<Array<RowDataPacket&{public_id:string;template_key:string;content_text:string;email:string}>>('SELECT t.public_id,t.template_key,t.content_text,u.email FROM email_template_tests t JOIN users u ON u.public_id=t.actor_public_id WHERE t.status=\'queued\' ORDER BY t.created_at LIMIT 1 FOR UPDATE');const row=rows[0];if(!row)return null;await c.execute("UPDATE email_template_tests SET status='processing',updated_at=UTC_TIMESTAMP() WHERE public_id=?",[row.public_id]);const key=keySchema.parse(row.template_key);return{testId:row.public_id,key,email:row.email,content:content(key,row.content_text)};});}
  async finishTest(testId:string,status:'sent'|'failed',errorCode?:string){await this.#pool.execute('UPDATE email_template_tests SET status=?,error_code=?,updated_at=UTC_TIMESTAMP() WHERE public_id=?',[status,errorCode??null,testId]);}
  async #transaction<T>(work:(c:PoolConnection)=>Promise<T>):Promise<T>{const c=await this.#pool.getConnection();try{await c.beginTransaction();const result=await work(c);await c.commit();return result;}catch(error){await c.rollback();throw error;}finally{c.release();}}
  async #idempotent(c:PoolConnection,actor:string,id:string,action:string,key:string,payload:unknown):Promise<unknown|null>{const[rows]=await c.execute<Array<RowDataPacket&{payload_hash:string;result_text:string}>>('SELECT payload_hash,result_text FROM email_template_actions WHERE actor_public_id=? AND action_key=? FOR UPDATE',[actor,id]);if(!rows[0])return null;if(rows[0].payload_hash!==hash(payload))throw new AppError(409,'IDEMPOTENCY_CONFLICT','Idempotency key digunakan dengan payload berbeda.');return JSON.parse(rows[0].result_text);}
  async #remember(c:PoolConnection,actor:string,id:string,action:string,key:string,payload:unknown,result:unknown,reason:string|null,requestId:string){await c.execute('INSERT INTO email_template_actions(actor_public_id,action_key,template_key,action,payload_hash,result_text,reason,request_id,created_at) VALUES(?,?,?,?,?,?,?,?,UTC_TIMESTAMP())',[actor,id,key,action,hash(payload),JSON.stringify(result),reason,requestId]);}
}
const version=(row:VersionRow):TemplateVersion=>({version:Number(row.version),content:JSON.parse(row.content_text) as EmailContent,actorPublicId:row.actor_public_id,reason:row.reason,createdAt:row.created_at});
const missing=(message='Template tidak ditemukan.')=>new AppError(404,'EMAIL_TEMPLATE_NOT_FOUND',message);
const conflict=()=>new AppError(409,'EMAIL_TEMPLATE_CONFLICT','Template berubah di sesi lain. Muat ulang dan rekonsiliasi perubahan.');
