import type{Request,Response}from'express';import{z}from'zod';import{readCookie}from'../../../shared/http/cookie-reader.ts';import{AppError}from'../../../shared/http/errors.ts';import type{AuthenticatedActorService}from'../../../shared/security/authenticated-actor.ts';import{slugInputSchema,suggestionQuerySchema,themeInputSchema}from'../dto/customization-input.ts';import type{CardCustomizationService}from'../services/card-customization-service.ts';
const idSchema=z.uuid();
export class CardCustomizationController{readonly #service:CardCustomizationService;readonly #actors:AuthenticatedActorService;constructor(service:CardCustomizationService,actors:AuthenticatedActorService){this.#service=service;this.#actors=actors;}
suggestion=async(req:Request,res:Response)=>{this.#safe(req);const data=this.#parse(suggestionQuerySchema,req.query);res.json({success:true,message:'Slug suggestion generated.',data:this.#service.suggest(data.fullName,data.mobilePhone)});};
availability=async(req:Request,res:Response)=>{this.#safe(req);const slug=typeof req.query.slug==='string'?req.query.slug:'';res.json({success:true,message:'Slug availability checked.',data:await this.#service.availability(slug)});};
updateSlug=async(req:Request,res:Response)=>{const actor=this.#unsafe(req);const data=this.#parse(slugInputSchema,req.body);res.json({success:true,message:'Card slug updated.',data:await this.#service.updateSlug(actor.userPublicId,this.#id(req),data.slug)});};
catalog=async(req:Request,res:Response)=>{const actor=this.#safe(req);res.json({success:true,message:'Themes retrieved.',data:await this.#service.catalog(actor.userPublicId)});};
cardThemes=async(req:Request,res:Response)=>{const actor=this.#safe(req);res.json({success:true,message:'Card themes retrieved.',data:await this.#service.cardThemes(actor.userPublicId,this.#id(req))});};
updateTheme=async(req:Request,res:Response)=>{const actor=this.#unsafe(req);const data=this.#parse(themeInputSchema,req.body);res.json({success:true,message:'Card theme updated.',data:await this.#service.updateTheme(actor.userPublicId,this.#id(req),data.themeCode)});};
#safe(req:Request){return this.#actors.authenticate(readCookie(req,'access_token')??undefined);}#unsafe(req:Request){return this.#actors.authorizeUnsafe(readCookie(req,'access_token')??undefined,req.header('x-csrf-token'));}#id(req:Request){return this.#parse(idSchema,req.params.publicId);}#parse<T>(schema:z.ZodType<T>,value:unknown):T{const parsed=schema.safeParse(value);if(!parsed.success)throw new AppError(422,'VALIDATION_ERROR','Validation failed.',parsed.error.issues.map(issue=>({field:issue.path.join('.'),message:issue.message})));return parsed.data;}}
