import type { Pool, PoolConnection, ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import type { NormalizedCardInput as CardInput } from '../dto/card-input.ts';
import type { CardRepository, CardTransaction, EntitledUser, OwnedCard, ThemeOption } from './card-repository.ts';

type CardRow = RowDataPacket & { id:number; public_id:string; slug:string; plan_code:'starter'|'basic'|'pro'; theme_code:string; locale:'id'|'en'; status:string;logo_path:string|null; full_name:string; job_title:string; organization:string; office_phone:string; mobile_phone:string; email:string; website_url:string; address_text:string;maps_url:string|null };
const selectCard = `SELECT c.id,c.public_id,c.slug,c.plan_code,t.code theme_code,c.locale,c.status,c.logo_path,cc.full_name,cc.job_title,cc.organization,cc.office_phone,cc.mobile_phone,cc.email,cc.website_url,cc.address_text,cc.maps_url FROM cards c JOIN users u ON u.id=c.user_id JOIN themes t ON t.id=c.theme_id JOIN card_contacts cc ON cc.card_id=c.id`;
const selectPublicCard = `SELECT c.id,c.public_id,c.slug,c.plan_code,t.code theme_code,c.locale,c.status,c.logo_path,cc.full_name,cc.job_title,cc.organization,cc.office_phone,cc.mobile_phone,cc.email,cc.website_url,cc.address_text,cc.maps_url FROM cards c JOIN themes t ON t.id=c.theme_id JOIN card_contacts cc ON cc.card_id=c.id`;
function map(row: CardRow): OwnedCard { return { id:row.id, publicId:row.public_id, slug:row.slug, planCode:row.plan_code, themeCode:row.theme_code, locale:row.locale, status:row.status,logoPath:row.logo_path, contact:{ fullName:row.full_name, jobTitle:row.job_title, organization:row.organization, officePhone:row.office_phone, mobilePhone:row.mobile_phone, email:row.email, websiteUrl:row.website_url, addressText:row.address_text,mapsUrl:row.maps_url } }; }

class MySqlCardTransaction implements CardTransaction {
  readonly connection: PoolConnection;
  constructor(connection: PoolConnection) { this.connection = connection; }
  async findEntitledUserForUpdate(publicId:string): Promise<EntitledUser|null> { const [rows]=await this.connection.execute<(RowDataPacket & {id:number;plan_code:'basic'|'pro'})[]>(`SELECT u.id,p.code plan_code FROM users u JOIN subscriptions s ON s.user_id=u.id JOIN plans p ON p.id=s.plan_id WHERE u.public_id=? AND u.status='active' AND u.email_verified_at IS NOT NULL AND s.status='active' AND s.starts_at<=UTC_TIMESTAMP() AND (s.ends_at IS NULL OR s.ends_at>UTC_TIMESTAMP()) AND p.code IN ('basic','pro') AND p.is_active=1 ORDER BY s.ends_at DESC LIMIT 1 FOR UPDATE`,[publicId]); return rows[0] ? {id:rows[0].id,planCode:rows[0].plan_code}:null; }
  async userHasActiveCard(userId:number):Promise<boolean>{const [rows]=await this.connection.execute<RowDataPacket[]>(`SELECT id FROM cards WHERE user_id=? AND deleted_at IS NULL AND status<>'deleted' LIMIT 1 FOR UPDATE`,[userId]);return rows.length>0;}
  async findDefaultTheme(planCode:'basic'|'pro'){const [rows]=await this.connection.execute<(RowDataPacket&{id:number;code:string})[]>(`SELECT t.id,t.code FROM themes t JOIN plan_theme_access pta ON pta.theme_id=t.id JOIN plans p ON p.id=pta.plan_id WHERE p.code=? AND p.is_active=1 AND t.is_active=1 ORDER BY t.display_order,t.id LIMIT 1`,[planCode]);return rows[0]??null;}
  async slugExists(slug:string){const [rows]=await this.connection.execute<RowDataPacket[]>(`SELECT id FROM cards WHERE slug=? LIMIT 1`,[slug]);return rows.length>0;}
  async insertOwnedCard(input:{publicId:string;userId:number;planCode:'basic'|'pro';themeId:number;slug:string;data:CardInput;now:Date}):Promise<OwnedCard>{const {data,now}=input;const [result]=await this.connection.execute<ResultSetHeader>(`INSERT INTO cards(public_id,user_id,slug,slug_kind,plan_code,theme_id,locale,status,created_at,updated_at) VALUES(?,?,?,'custom',?,?,?,'draft',?,?)`,[input.publicId,input.userId,input.slug,input.planCode,input.themeId,data.locale,now,now]);await this.connection.execute(`INSERT INTO card_contacts(card_id,full_name,job_title,organization,office_phone,mobile_phone,email,website_url,address_text,maps_url,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,[result.insertId,data.contact.fullName,data.contact.jobTitle,data.contact.organization,data.contact.officePhone,data.contact.mobilePhone,data.contact.email,data.contact.websiteUrl,data.contact.addressText,data.contact.mapsUrl,now,now]);const [rows]=await this.connection.execute<CardRow[]>(`${selectCard} WHERE c.id=?`,[result.insertId]);return map(rows[0]!);}
}
export class MySqlCardRepository implements CardRepository {
  readonly pool: Pool;
  constructor(pool:Pool){this.pool=pool;}
  async transaction<T>(work:(transaction:CardTransaction)=>Promise<T>):Promise<T>{const connection=await this.pool.getConnection();try{await connection.beginTransaction();const result=await work(new MySqlCardTransaction(connection));await connection.commit();return result;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
  async listOwned(userPublicId:string){const [rows]=await this.pool.execute<CardRow[]>(`${selectCard} WHERE u.public_id=? AND c.deleted_at IS NULL AND c.status<>'deleted' ORDER BY c.id`,[userPublicId]);return rows.map(map);}
  async findOwned(userPublicId:string,publicId:string){const [rows]=await this.pool.execute<CardRow[]>(`${selectCard} WHERE u.public_id=? AND c.public_id=? AND c.deleted_at IS NULL AND c.status<>'deleted' LIMIT 1`,[userPublicId,publicId]);return rows[0]?map(rows[0]):null;}
  async updateOwned(userPublicId:string,publicId:string,data:CardInput,now:Date){const connection=await this.pool.getConnection();try{await connection.beginTransaction();const [cards]=await connection.execute<(RowDataPacket&{id:number})[]>(`SELECT c.id FROM cards c JOIN users u ON u.id=c.user_id WHERE u.public_id=? AND c.public_id=? AND c.deleted_at IS NULL AND c.status<>'deleted' LIMIT 1 FOR UPDATE`,[userPublicId,publicId]);if(!cards[0]){await connection.rollback();return null;}await connection.execute(`UPDATE cards SET locale=?,updated_at=? WHERE id=?`,[data.locale,now,cards[0].id]);await connection.execute(`UPDATE card_contacts SET full_name=?,job_title=?,organization=?,office_phone=?,mobile_phone=?,email=?,website_url=?,address_text=?,maps_url=?,updated_at=? WHERE card_id=?`,[data.contact.fullName,data.contact.jobTitle,data.contact.organization,data.contact.officePhone,data.contact.mobilePhone,data.contact.email,data.contact.websiteUrl,data.contact.addressText,data.contact.mapsUrl,now,cards[0].id]);const [rows]=await connection.execute<CardRow[]>(`${selectCard} WHERE c.id=?`,[cards[0].id]);await connection.commit();return map(rows[0]!);}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
  async softDeleteOwned(userPublicId:string,publicId:string,now:Date){const [result]=await this.pool.execute<ResultSetHeader>(`UPDATE cards c JOIN users u ON u.id=c.user_id SET c.status='deleted',c.deleted_at=?,c.updated_at=? WHERE u.public_id=? AND c.public_id=? AND c.deleted_at IS NULL`,[now,now,userPublicId,publicId]);return result.affectedRows===1;}
  async findEffectivePlan(userPublicId:string){const [rows]=await this.pool.execute<(RowDataPacket&{plan_code:'basic'|'pro'})[]>(`SELECT p.code plan_code FROM users u JOIN subscriptions s ON s.user_id=u.id JOIN plans p ON p.id=s.plan_id WHERE u.public_id=? AND u.status='active' AND u.email_verified_at IS NOT NULL AND s.status='active' AND s.starts_at<=UTC_TIMESTAMP() AND (s.ends_at IS NULL OR s.ends_at>UTC_TIMESTAMP()) AND p.code IN ('basic','pro') AND p.is_active=1 ORDER BY s.ends_at DESC LIMIT 1`,[userPublicId]);return rows[0]?.plan_code??null;}
  async isSlugAvailable(slug:string,excludePublicId?:string){const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT id FROM cards WHERE slug=? AND (? IS NULL OR public_id<>?) LIMIT 1`,[slug,excludePublicId??null,excludePublicId??null]);return rows.length===0;}
  async updateOwnedSlug(userPublicId:string,publicId:string,slug:string,now:Date){const [result]=await this.pool.execute<ResultSetHeader>(`UPDATE cards c JOIN users u ON u.id=c.user_id SET c.slug=?,c.slug_kind='custom',c.updated_at=? WHERE u.public_id=? AND c.public_id=? AND c.plan_code IN ('basic','pro') AND c.deleted_at IS NULL`,[slug,now,userPublicId,publicId]);return result.affectedRows===1?this.findOwned(userPublicId,publicId):null;}
  async listThemes(planCode:'starter'|'basic'|'pro'):Promise<ThemeOption[]>{const [rows]=await this.pool.execute<(RowDataPacket&{code:string;name:string;orientation:string;preview_path:string;display_order:number;is_available:number})[]>(`SELECT t.code,t.name,t.orientation,t.preview_path,t.display_order,EXISTS(SELECT 1 FROM plan_theme_access pta JOIN plans p ON p.id=pta.plan_id WHERE pta.theme_id=t.id AND p.code=? AND p.is_active=1) is_available FROM themes t WHERE t.is_active=1 ORDER BY t.display_order,t.id`,[planCode]);return rows.map(row=>({code:row.code,name:row.name,orientation:row.orientation,previewPath:row.preview_path,displayOrder:row.display_order,isAvailable:row.is_available===1}));}
  async updateOwnedTheme(userPublicId:string,publicId:string,themeCode:string,now:Date):Promise<OwnedCard|'forbidden'|null>{const card=await this.findOwned(userPublicId,publicId);if(!card)return null;const [themes]=await this.pool.execute<(RowDataPacket&{id:number})[]>(`SELECT t.id FROM themes t JOIN plan_theme_access pta ON pta.theme_id=t.id JOIN plans p ON p.id=pta.plan_id WHERE t.code=? AND t.is_active=1 AND p.code=? AND p.is_active=1 LIMIT 1`,[themeCode,card.planCode]);if(!themes[0])return'forbidden';await this.pool.execute(`UPDATE cards SET theme_id=?,updated_at=? WHERE id=?`,[themes[0].id,now,card.id]);return this.findOwned(userPublicId,publicId);}
  async publishOwned(userPublicId:string,publicId:string,now:Date){const [result]=await this.pool.execute<ResultSetHeader>(`UPDATE cards c JOIN users u ON u.id=c.user_id JOIN themes t ON t.id=c.theme_id SET c.status='published',c.published_at=COALESCE(c.published_at,?),c.updated_at=? WHERE u.public_id=? AND c.public_id=? AND c.deleted_at IS NULL AND c.status IN ('draft','published') AND t.is_active=1`,[now,now,userPublicId,publicId]);return result.affectedRows===1?this.findOwned(userPublicId,publicId):null;}
  async findPublished(slug:string){const [rows]=await this.pool.execute<CardRow[]>(`${selectPublicCard} WHERE c.slug=BINARY ? AND c.status='published' AND c.deleted_at IS NULL AND t.is_active=1 LIMIT 1`,[slug]);return rows[0]?map(rows[0]):null;}
  async updateOwnedLogo(userPublicId:string,publicId:string,logoPath:string,now:Date){const current=await this.findOwned(userPublicId,publicId);if(!current)return null;const[result]=await this.pool.execute<ResultSetHeader>(`UPDATE cards c JOIN users u ON u.id=c.user_id SET c.logo_path=?,c.updated_at=? WHERE u.public_id=? AND c.public_id=? AND c.plan_code='pro' AND c.deleted_at IS NULL`,[logoPath,now,userPublicId,publicId]);if(result.affectedRows!==1)return null;const card=await this.findOwned(userPublicId,publicId);return card?{card,previousPath:current.logoPath??null}:null;}
}
