import { createHash, randomUUID } from 'node:crypto';
import { AppError } from '../../../shared/http/errors.ts';
import type { CheckoutInput } from '../dto/payment-input.ts';
import type { PaymentGatewayPort } from '../gateways/payment-gateway-port.ts';
import type { PaymentRecord, PaymentRepository } from '../repositories/payment-repository.ts';

export type CheckoutResponse = PaymentRecord & { snapToken: string };
const UPGRADE_PRICES: Record<string, number> = {
  'starter:basic': 55000,
  'starter:pro': 97000,
  'basic:pro': 55000,
};

export class PaymentService {
  readonly #repository:PaymentRepository;readonly #gateway:PaymentGatewayPort|undefined;readonly #callbacks:{finish:string;unfinish:string;error:string};
  constructor(deps:{repository:PaymentRepository;gateway?:PaymentGatewayPort;callbacks:{finish:string;unfinish:string;error:string}}){this.#repository=deps.repository;this.#gateway=deps.gateway;this.#callbacks=deps.callbacks;}
  async checkout(userPublicId:string,input:CheckoutInput):Promise<CheckoutResponse>{if(!this.#gateway)throw new AppError(503,'PAYMENT_GATEWAY_UNAVAILABLE','Payment gateway is unavailable.');const authority=await this.#repository.findCheckoutAuthority(userPublicId,input.planCode);if(!authority)throw new AppError(403,'CHECKOUT_NOT_ALLOWED','A verified account with a claimed active card is required.');if(authority.targetPlan.durationDays!==365)throw new AppError(409,'PLAN_NOT_PURCHASABLE','The selected annual plan is not configured for a 365-day term.');const upgradePrice=UPGRADE_PRICES[`${authority.currentPlanCode}:${input.planCode}`];if(!upgradePrice)throw new AppError(409,'PLAN_UPGRADE_NOT_AVAILABLE','No upgrade checkout is available for the current membership.');const checkoutAuthority={...authority,targetPlan:{...authority.targetPlan,amount:upgradePrice}};const publicId=randomUUID(),merchantOrderId=`KND_${randomUUID().replaceAll('-','')}`;const pending=await this.#repository.insertPending({publicId,merchantOrderId,authority:checkoutAuthority,now:new Date()});try{const gateway=await this.#gateway.createCheckout({orderId:merchantOrderId,amount:upgradePrice,customer:{email:authority.email,firstName:authority.fullName},item:{id:authority.targetPlan.code,name:`Upgrade ${authority.currentPlanCode.toUpperCase()} ke ${authority.targetPlan.name}`,quantity:1,price:upgradePrice},callbacks:this.#callbacks});const updated=await this.#repository.attachGatewayCheckout(publicId,gateway.redirectUrl,null,new Date());if(!updated)throw new AppError(500,'PAYMENT_PERSISTENCE_FAILED','Payment could not be persisted.');return{...updated,snapToken:gateway.token};}catch(error){await this.#repository.markCheckoutFailed(publicId,new Date());throw error;}}
  list(userPublicId:string){return this.#repository.listOwned(userPublicId);}
  async get(userPublicId:string,publicId:string){const result=await this.#repository.findOwned(userPublicId,publicId);if(!result)throw new AppError(404,'PAYMENT_NOT_FOUND','Payment not found.');return result;}
  async notification(payload:unknown){if(!this.#gateway)throw new AppError(503,'PAYMENT_GATEWAY_UNAVAILABLE','Payment gateway is unavailable.');const verified=await this.#gateway.verifyNotification(payload);const payloadHash=createHash('sha256').update(JSON.stringify(verified.raw)).digest('hex');const outcome=await this.#repository.applyVerifiedNotification(verified,payloadHash,new Date());if(outcome.result==='unknown_order')throw new AppError(400,'PAYMENT_ORDER_UNKNOWN','Payment order is unknown.');if(outcome.result==='amount_mismatch')throw new AppError(400,'PAYMENT_AMOUNT_MISMATCH','Payment notification amount does not match.');if(outcome.result==='event_conflict')throw new AppError(409,'PAYMENT_EVENT_CONFLICT','Payment event conflicts with a prior notification.');return outcome;}
  async reconcile(userPublicId:string,publicId:string){if(!this.#gateway)throw new AppError(503,'PAYMENT_GATEWAY_UNAVAILABLE','Payment gateway is unavailable.');const payment=await this.get(userPublicId,publicId);const status=await this.#gateway.getTransactionStatus(payment.merchantOrderId);const eventKey=createHash('sha256').update(`reconcile|${status.orderId}|${status.transactionId??''}|${status.statusCode}|${status.transactionStatus}`).digest('hex');const payloadHash=createHash('sha256').update(JSON.stringify(status.raw)).digest('hex');const outcome=await this.#repository.applyVerifiedNotification({...status,eventKey},payloadHash,new Date());if(outcome.result==='amount_mismatch')throw new AppError(400,'PAYMENT_AMOUNT_MISMATCH','Payment status amount does not match.');if(outcome.result==='event_conflict')throw new AppError(409,'PAYMENT_EVENT_CONFLICT','Payment event conflicts with a prior status.');return outcome;}
  currentSubscription(userPublicId:string){return this.#repository.findCurrentSubscription(userPublicId,new Date());}
}
