import type{Request,Response}from'express';import{z}from'zod';import{readCookie}from'../../../shared/http/cookie-reader.ts';import{AppError}from'../../../shared/http/errors.ts';import type{AuthenticatedActorService}from'../../../shared/security/authenticated-actor.ts';import type{RbacService}from'../../../shared/security/rbac-service.ts';import type{SuperAdminService}from'../services/super-admin-service.ts';
const intervention=z.object({action:z.enum(['SUSPEND_USER','ACTIVATE_USER','GRANT_ROLE','EXTEND_SUBSCRIPTION','RESET_RESUME_ENTITLEMENT']),reason:z.string().trim().min(10).max(1000),roleCode:z.string().max(60).optional(),days:z.number().int().positive().max(3650).optional(),confirm:z.literal(true)}).strict();
const setting=z.object({value:z.string().max(10000).nullable(),reason:z.string().trim().min(10).max(1000),confirm:z.literal(true)}).strict();
export class SuperAdminController{
  readonly service:SuperAdminService;readonly actors:AuthenticatedActorService;readonly rbac:RbacService;
  constructor(service:SuperAdminService,actors:AuthenticatedActorService,rbac:RbacService){this.service=service;this.actors=actors;this.rbac=rbac;}
  statistics=async(req:Request,res:Response)=>{const a=this.#safe(req);res.json({success:true,message:'Operational statistics retrieved.',data:await this.service.statistics(a.userPublicId)});};
  user=async(req:Request,res:Response)=>{const a=this.#safe(req);res.json({success:true,message:'User detail retrieved.',data:await this.service.user(a.userPublicId,String(req.params.publicId))});};
  specialists=async(req:Request,res:Response)=>{const a=this.#safe(req);res.json({success:true,message:'CV specialists retrieved.',data:await this.service.specialists(a.userPublicId)});};
  subscriptions=async(req:Request,res:Response)=>{const a=this.#safe(req);res.json({success:true,message:'Subscriptions retrieved.',data:await this.service.subscriptions(a.userPublicId)});};
  usage=async(req:Request,res:Response)=>{const a=this.#safe(req);res.json({success:true,message:'Usage adjustments retrieved.',data:await this.service.usage(a.userPublicId)});};
  interventions=async(req:Request,res:Response)=>{const a=this.#safe(req);res.json({success:true,message:'Interventions retrieved.',data:await this.service.interventions(a.userPublicId)});};
  settings=async(req:Request,res:Response)=>{const a=this.#safe(req);res.json({success:true,message:'Sanitized settings retrieved.',data:await this.service.settings(a.userPublicId)});};
  updateSetting=async(req:Request,res:Response)=>{const a=this.#unsafe(req),p=setting.safeParse(req.body);if(!p.success)throw new AppError(422,'VALIDATION_ERROR','Validation failed.');await this.rbac.assertRecentSession(a.userPublicId,a.sessionId);res.json({success:true,message:'Setting updated.',data:await this.service.updateSetting(a.userPublicId,String(req.params.key),p.data.value,p.data.reason)});};
  intervene=async(req:Request,res:Response)=>{const a=this.#unsafe(req),p=intervention.safeParse(req.body);if(!p.success)throw new AppError(422,'VALIDATION_ERROR','Validation failed.');await this.rbac.assertRecentSession(a.userPublicId,a.sessionId);res.json({success:true,message:'Controlled intervention applied.',data:await this.service.intervene(a.userPublicId,String(req.params.publicId),p.data,String(res.locals.requestId??''))});};
  #safe(req:Request){return this.actors.authenticate(readCookie(req,'access_token')??undefined);}#unsafe(req:Request){return this.actors.authorizeUnsafe(readCookie(req,'access_token')??undefined,req.header('x-csrf-token'));}
}
