import{unlink}from'node:fs/promises';import{randomUUID}from'node:crypto';
import type{RowDataPacket}from'mysql2/promise';
import{loadEnvironment}from'../src/config/environment.ts';import{createDatabasePool}from'../src/shared/database/pool.ts';import{jsonLogger}from'../src/shared/logging/logger.ts';
const pool=createDatabasePool(loadEnvironment()),now=new Date();
try{
  const [warnings]=await pool.execute<Array<RowDataPacket&{id:number;user_id:number;email:string;public_id:string;retention_expires_at:Date;days:number}>>(`SELECT r.id,r.user_id,r.account_email_snapshot email,r.public_id,r.retention_expires_at,TIMESTAMPDIFF(DAY,UTC_TIMESTAMP(),r.retention_expires_at) days FROM resume_requests r WHERE r.status='COMPLETED' AND r.retention_expires_at>UTC_TIMESTAMP() AND TIMESTAMPDIFF(DAY,UTC_TIMESTAMP(),r.retention_expires_at) IN (30,7,1)`);
  for(const row of warnings){const c=await pool.getConnection();try{await c.beginTransaction();const[result]=await c.execute(`INSERT IGNORE INTO resume_retention_notices(request_id,threshold_days,queued_at) VALUES(?,?,?)`,[row.id,row.days,now]);if('affectedRows'in result&&result.affectedRows===1)await c.execute(`INSERT INTO mail_outbox(public_id,user_id,template_key,recipient_email,subject,payload_text,priority,status,attempts,max_attempts,available_at,created_at,updated_at) VALUES(?,?,?,?,?,?,50,'queued',0,3,?,?,?)`,[randomUUID(),row.user_id,`resume.retention-${row.days}-days`,row.email,'Masa unduh Resume Enhancement',JSON.stringify({requestPublicId:row.public_id,retentionExpiresAt:row.retention_expires_at.toISOString()}),now,now,now]);await c.commit();}catch(e){await c.rollback();throw e;}finally{c.release();}}
  const [expired]=await pool.execute<Array<RowDataPacket&{id:number;storage_path:string}>>(`SELECT r.id,f.storage_path FROM resume_requests r JOIN resume_request_files f ON f.resume_request_id=r.id AND f.deleted_at IS NULL WHERE r.status='COMPLETED' AND r.retention_expires_at<=UTC_TIMESTAMP()`);
  const grouped=new Map<number,string[]>();for(const row of expired)grouped.set(row.id,[...(grouped.get(row.id)??[]),row.storage_path]);
  for(const [id,paths]of grouped){let failed=false;for(const path of paths)try{await unlink(path);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT'){failed=true;jsonLogger.error('resume.cleanup_failed',{request_id:id,code:(e as NodeJS.ErrnoException).code??'UNKNOWN'});}}if(!failed){await pool.execute(`UPDATE resume_request_files SET deleted_at=? WHERE resume_request_id=? AND deleted_at IS NULL`,[now,id]);await pool.execute(`UPDATE resume_requests SET status='EXPIRED',expired_at=?,updated_at=? WHERE id=? AND status='COMPLETED'`,[now,now,id]);}}
  jsonLogger.info('resume.worker_completed',{warnings:warnings.length,expired_requests:grouped.size});
}finally{await pool.end();}
