import assert from 'node:assert/strict';import type{AddressInfo}from'node:net';import test from'node:test';import{createApp}from'../../src/app.ts';import{CardController}from'../../src/modules/cards/controllers/card-controller.ts';import{CardCustomizationController}from'../../src/modules/cards/controllers/card-customization-controller.ts';import{createCardRouter}from'../../src/modules/cards/routes/card-router.ts';import type{CardService}from'../../src/modules/cards/services/card-service.ts';import type{CardCustomizationService}from'../../src/modules/cards/services/card-customization-service.ts';import{AppError}from'../../src/shared/http/errors.ts';import type{Logger}from'../../src/shared/logging/logger.ts';import type{AuthenticatedActorService}from'../../src/shared/security/authenticated-actor.ts';
const silent:Logger={info:()=>undefined,error:()=>undefined};const id='7fe91d39-c2a8-4b29-bc1d-b5304c7bfc61';
const actors={authenticate:(token?:string)=>{if(!token)throw new AppError(401,'AUTH_REQUIRED','Authentication is required.');return{userPublicId:'user',sessionId:'session',role:'user' as const};},authorizeUnsafe:(token?:string,csrf?:string)=>{if(!token)throw new AppError(401,'AUTH_REQUIRED','Authentication is required.');if(csrf!=='valid')throw new AppError(403,'CSRF_INVALID','CSRF validation failed.');return{userPublicId:'user',sessionId:'session',role:'user' as const};}}as AuthenticatedActorService;
const customization={suggest:(name:string,phone:string)=>({suggestion:`${name.slice(0,2).toLowerCase()}${phone}`,alternatives:['safe-one'],exposesMobilePhone:true,privacyWarning:'phone number'}),availability:async(slug:string)=>({slug,available:true,alternatives:[]}),updateSlug:async()=>({publicId:id,slug:'new-slug'}),catalog:async()=>[],cardThemes:async()=>[],updateTheme:async()=>({publicId:id,themeCode:'basic-blue-line'})}as unknown as CardCustomizationService;
const cards={list:async()=>[],create:async()=>undefined,get:async()=>undefined,update:async()=>undefined,delete:async()=>undefined}as unknown as CardService;
async function call(method:string,path:string,body?:unknown,headers:Record<string,string>={}){const router=createCardRouter(new CardController(cards,actors),new CardCustomizationController(customization,actors));const app=createApp({databaseHealth:{check:async()=>({healthy:true,latencyMs:0})},environment:'testing',logger:silent,cardRouter:router});const server=app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));try{const port=(server.address()as AddressInfo).port;return await fetch(`http://127.0.0.1:${port}${path}`,{method,headers:{'content-type':'application/json',cookie:'access_token=valid',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});}finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}}
test('static slug-suggestion route is not captured as publicId',async()=>{const response=await call('GET','/api/v1/cards/slug-suggestion?fullName=Arwan&mobilePhone=0812');assert.equal(response.status,200);const body=await response.json()as{data:{exposesMobilePhone:boolean}};assert.equal(body.data.exposesMobilePhone,true);});
test('unsafe slug and theme mutations require CSRF',async()=>{assert.equal((await call('PATCH',`/api/v1/cards/${id}/slug`,{slug:'new-slug'})).status,403);assert.equal((await call('PATCH',`/api/v1/cards/${id}/theme`,{themeCode:'basic-blue-line'})).status,403);});
test('slug mutation rejects unknown fields before service',async()=>{const response=await call('PATCH',`/api/v1/cards/${id}/slug`,{slug:'new-slug',planCode:'pro'},{'x-csrf-token':'valid'});assert.equal(response.status,422);});
test('theme mutation returns selected theme through authenticated route',async()=>{const response=await call('PATCH',`/api/v1/cards/${id}/theme`,{themeCode:'basic-blue-line'},{'x-csrf-token':'valid'});assert.equal(response.status,200);});
